/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca;

/**
 *
 * @author Dell
 */
public class InformacionUsuario extends javax.swing.JFrame {

    /**
     * Creates new form InformacionUsuario
     */
    public InformacionUsuario() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setTitle("Registro");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInformaciondeUsuario1 = new javax.swing.JPanel();
        chkNombredeUsuario1 = new javax.swing.JCheckBox();
        chkFechadeNacimiento1 = new javax.swing.JCheckBox();
        chkGeneroFavorito1 = new javax.swing.JCheckBox();
        chkContra1 = new javax.swing.JCheckBox();
        chkTelefono1 = new javax.swing.JCheckBox();
        chkNombreCompleto1 = new javax.swing.JCheckBox();
        chkCorreoElectronico1 = new javax.swing.JCheckBox();
        chkColecciondeLibros1 = new javax.swing.JCheckBox();
        chkAmigos1 = new javax.swing.JCheckBox();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));

        pnlInformaciondeUsuario1.setBackground(new java.awt.Color(0, 255, 204));
        pnlInformaciondeUsuario1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informacion del Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        chkNombredeUsuario1.setText("Nombre de usuario:");

        chkFechadeNacimiento1.setText("Fecha de nacimiento");

        chkGeneroFavorito1.setText("Genero favorito:");

        chkContra1.setText("Contraseña:");
        chkContra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkContra1ActionPerformed(evt);
            }
        });

        chkTelefono1.setText("Telefono:");

        chkNombreCompleto1.setText("Nombre completo:");

        chkCorreoElectronico1.setText("Correo electronico:");

        chkColecciondeLibros1.setText("Coleccion de libros:");

        chkAmigos1.setText("Amigos:");

        btnGuardar.setText("Guardar");

        javax.swing.GroupLayout pnlInformaciondeUsuario1Layout = new javax.swing.GroupLayout(pnlInformaciondeUsuario1);
        pnlInformaciondeUsuario1.setLayout(pnlInformaciondeUsuario1Layout);
        pnlInformaciondeUsuario1Layout.setHorizontalGroup(
            pnlInformaciondeUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformaciondeUsuario1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInformaciondeUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformaciondeUsuario1Layout.createSequentialGroup()
                        .addGroup(pnlInformaciondeUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInformaciondeUsuario1Layout.createSequentialGroup()
                                .addComponent(chkFechadeNacimiento1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlInformaciondeUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkNombreCompleto1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(chkTelefono1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(chkColecciondeLibros1, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(pnlInformaciondeUsuario1Layout.createSequentialGroup()
                                .addGroup(pnlInformaciondeUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlInformaciondeUsuario1Layout.createSequentialGroup()
                                        .addComponent(chkNombredeUsuario1)
                                        .addGap(26, 26, 26)
                                        .addComponent(chkContra1))
                                    .addComponent(chkCorreoElectronico1)
                                    .addComponent(chkGeneroFavorito1))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addGroup(pnlInformaciondeUsuario1Layout.createSequentialGroup()
                        .addComponent(chkAmigos1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar)
                        .addGap(35, 35, 35))))
        );
        pnlInformaciondeUsuario1Layout.setVerticalGroup(
            pnlInformaciondeUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformaciondeUsuario1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInformaciondeUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkNombredeUsuario1)
                    .addComponent(chkContra1))
                .addGap(18, 18, 18)
                .addGroup(pnlInformaciondeUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkTelefono1)
                    .addComponent(chkFechadeNacimiento1))
                .addGap(18, 18, 18)
                .addGroup(pnlInformaciondeUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkCorreoElectronico1)
                    .addComponent(chkNombreCompleto1))
                .addGap(18, 18, 18)
                .addGroup(pnlInformaciondeUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkGeneroFavorito1)
                    .addComponent(chkColecciondeLibros1))
                .addGap(18, 18, 18)
                .addGroup(pnlInformaciondeUsuario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkAmigos1)
                    .addComponent(btnGuardar))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlInformaciondeUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlInformaciondeUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkContra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkContra1ActionPerformed
        
    }//GEN-LAST:event_chkContra1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JCheckBox chkAmigos1;
    private javax.swing.JCheckBox chkColecciondeLibros1;
    private javax.swing.JCheckBox chkContra1;
    private javax.swing.JCheckBox chkCorreoElectronico1;
    private javax.swing.JCheckBox chkFechadeNacimiento1;
    private javax.swing.JCheckBox chkGeneroFavorito1;
    private javax.swing.JCheckBox chkNombreCompleto1;
    private javax.swing.JCheckBox chkNombredeUsuario1;
    private javax.swing.JCheckBox chkTelefono1;
    private javax.swing.JPanel pnlInformaciondeUsuario1;
    // End of variables declaration//GEN-END:variables
}
